### PR TITLE
Fix invalid JSON struct tag, and other linter issues

### LINKED ISSUE #317: Fix any linter issues and add missing GoDoc comments
While doing some of the work to add `context.Context` to the repo, I found a few cases where the linters on my system flagged some things to be changed.

I think it makes sense to make this the final change that goes into v1.4.0.

### PR DESCRIPTION
**Pull request by theckman**
This change is a pretty noisy change in that I went through and cleaned up all
of the issues that my linters flagged. I wanted to get this done, so that we can
add them as automatic CI checks for future PRs.

In the process I did find one critical bug, where we had a malformed JSON struct
tag:

https://github.com/PagerDuty/go-pagerduty/blob/69ade4b95ef0ff1d582a7d9f226a98f9db886df1/webhook.go#L44

There are two linter issues we cannot fix until v1.5.0, because they are
breaking changes. As such, the v1.5.0 development line would be the first place
we can enforce those CI checks.

Fixes #317

### CODE REVIEW

File: ability.go [hunk 1]
```diff
@@ -28,12 +28,12 @@ func (c *Client) ListAbilitiesWithContext(ctx context.Context) (*ListAbilityResp
...
 }
 
-// TestAbility Check if your account has the given ability.
+// TestAbility checks if your account has the given ability.
 func (c *Client) TestAbility(ability string) error {
 	return c.TestAbilityWithContext(context.Background(), ability)
 }
 
-// TestAbility Check if your account has the given ability.
+// TestAbilityWithContext checks if your account has the given ability.
```
Comment (theckman) [inline ability.go:36]: This was flagged by `golint`.

File: ability_test.go [hunk 2]
```diff
@@ -12,14 +12,13 @@ func TestAbility_ListAbilities(t *testing.T) {
 
 	mux.HandleFunc("/abilities", func(w http.ResponseWriter, r *http.Request) {
 		testMethod(t, r, "GET")
-		w.Write([]byte(`{"abilities": ["sso"]}`))
+		_, _ = w.Write([]byte(`{"abilities": ["sso"]}`))
```
Comment (theckman) [inline ability_test.go:15]: This was flagged by `errcheck`, which finds places where error checking was missed.

File: ability_test.go [hunk 3]
```diff
@@ -12,14 +12,13 @@ func TestAbility_ListAbilities(t *testing.T) {
...
 	})
 
-	var client = &Client{apiEndpoint: server.URL, authToken: "foo", HTTPClient: defaultHTTPClient}
+	client := &Client{apiEndpoint: server.URL, authToken: "foo", HTTPClient: defaultHTTPClient}
```
Comment (theckman) [inline ability_test.go:18]: My editor uses `gofumpt` instead of `go fmt` for style*, and it's a bit more opinionated. This was changed automatically.

* Technically it's `gofumports`, which is meant to replace `goimports`.

File: analytics_test.go [hunk 4]
```diff
@@ -30,14 +30,17 @@ func TestAnalytics_GetAggregatedIncidentData(t *testing.T) {
 	}
 
 	bytesAnalyticsResponse, err := json.Marshal(analyticsResponse)
+	testErrCheck(t, "json.Marshal()", "", err)
```
Comment (theckman) [inline analytics_test.go:33]: The ineffective assignment linter caught that we weren't handling the `err` value above; this is absolutely a bug.

File: client.go [hunk 5]
```diff
@@ -54,6 +54,8 @@ type APIReference struct {
 	Type string `json:"type,omitempty"`
 }
 
+// APIDetails are the fields required to represent a details non-hydrated
+// object.
```
Comment (theckman) [inline client.go:58]: This was caught by `golint`.

File: analytics_test.go [hunk 6]
```diff
@@ -30,14 +30,17 @@ func TestAnalytics_GetAggregatedIncidentData(t *testing.T) {
...
 	mux.HandleFunc("/analytics/metrics/incidents/all", func(w http.ResponseWriter, r *http.Request) {
 		testMethod(t, r, "POST")
-		w.Write(bytesAnalyticsResponse)
+		_, _ = w.Write(bytesAnalyticsResponse)
 	})
 
-	client := &Client{apiEndpoint: server.URL,
-		authToken:  "foo",
-		HTTPClient: defaultHTTPClient,
+	client := &Client{
```
Comment (theckman) [inline analytics_test.go:40]: This change was also `gofumports`.

**Review by theckman — COMMENTED** [review]
I added comments to indicate which linters / formatters caused some changes.

**Comment by theckman** [comment]
@stmcallister wanted to ping again to see if you may have a moment to :eyes: this week. I apologize for it being such a large PR, thankfully the majority of changes were done by automatic tooling and not by hand.

**Review by stmcallister — APPROVED** [review]
Looks good! Reading through the lint changes was educational for me. 😁 Also, thanks for catching the webhook bug and bumping the version up to 1.4.0.
